[project]
name = "modbus2mqtt"
version = "0.0.1"
description = ""
authors = [
	{ name = "Tobias Müller", email = "Tobias_Mueller@twam.info" }
]
license = "MIT"
requires-python = ">=3.12"
dependencies = [
	"PyYAML>=6.0,<7",
	"paho-mqtt>=1.0,<2", # asyncio-mqtt isn't working with 2, yet
	"aiomqtt>=2.0.0,<3",
	"pymodbus>=3.10.0,<3.11",
	"construct>=2.10.70,<3",
]

[project.scripts]
modbus2mqtt = 'modbus2mqtt.modbus2mqtt:main'

[dependency-groups]
dev= [
	"ruff",
	"pytest",
	"pytest-mock",
	"pytest-asyncio",
]

[build-system]
requires = ["uv_build>=0.8.17,<0.9.0"]
build-backend = "uv_build"
[tool.ruff]
line-length = 140

[tool.ruff.lint]
# "ANN", 
select = ["F", "E", "W", "I", "N", "UP", "YTT", "ASYNC", "BLE", "FBT", "B", "COM", "C4", "DTZ", "EM", "EXE", "FA", "ISC", "ICN", "LOG", "G", "INP", "PIE", "PT", "Q", "RSE", "RET", "SLF", "SLOT", "SIM", "TID", "INT", "ARG", "PTH", "FIX", "ERA", "NPY", "RUF"]
ignore = ["EXE002", "G004"]

